In [71]:
import numpy as np

earth2893 =np.array( [[1, 4, 3, 2, 9],[0, 0, 6, 0, 7],[8, 9, 0, 1 , 9],[3, 1, 0, 5, 8]])

In [72]:
print(earth2893)

[[1 4 3 2 9]
 [0 0 6 0 7]
 [8 9 0 1 9]
 [3 1 0 5 8]]


In [73]:


def label_to_coords(label):
    x = (label - 1) % dimension
    y = (label - 1 - x) // dimension
    return x, y

def coords_to_label(x, y):
    return x + dimension * y + 1


def get_ind(given_index):
    result = []
    x, y = label_to_coords(given_index)
    for delta_x in range(-1, 2):
        for delta_y in range(-1, 2):
            if not (delta_x == delta_y == 0):
                new_x = x + delta_x
                new_y = y + delta_y
                if (0 <= new_x < dimension) and (0 <= new_y < dimension):
                    result.append(coords_to_label(new_x, new_y))
    return result



In [74]:
#label_to_coords(earth2893)

In [75]:
def explore(self):
    for i in self:
        dimension=len(i)
        i.sort()
        i=i[::-1]
        print("Cell = ", i)
        print("Start =", (i[0]))
       
        for a in range(0,len(i)-1) :
            print("Collect =", (i[a]), "plants")
            print("Looks at :", get_ind(i[a]))
            if  (a < len(i) ):
                print("Moves to :", i[a+1])
            
    return("Wait for Mama")

In [76]:
#dimension=len(earth2893)
explore(earth2893)

Cell =  [9 4 3 2 1]
Start = 9
Collect = 9 plants
Looks at : [5, 13, 6, 10, 14]
Moves to : 4
Collect = 4 plants
Looks at : [3, 7, 8]
Moves to : 3
Collect = 3 plants
Looks at : [2, 6, 7, 4, 8]
Moves to : 2
Collect = 2 plants
Looks at : [1, 5, 6, 3, 7]
Moves to : 1
Cell =  [7 6 0 0 0]
Start = 7
Collect = 7 plants
Looks at : [2, 6, 10, 3, 11, 4, 8, 12]
Moves to : 6
Collect = 6 plants
Looks at : [1, 5, 9, 2, 10, 3, 7, 11]
Moves to : 0
Collect = 0 plants
Looks at : [3, 4]
Moves to : 0
Collect = 0 plants
Looks at : [3, 4]
Moves to : 0
Cell =  [9 9 8 1 0]
Start = 9
Collect = 9 plants
Looks at : [5, 13, 6, 10, 14]
Moves to : 9
Collect = 9 plants
Looks at : [5, 13, 6, 10, 14]
Moves to : 8
Collect = 8 plants
Looks at : [3, 7, 11, 4, 12]
Moves to : 1
Collect = 1 plants
Looks at : [5, 2, 6]
Moves to : 0
Cell =  [8 5 3 1 0]
Start = 8
Collect = 8 plants
Looks at : [3, 7, 11, 4, 12]
Moves to : 5
Collect = 5 plants
Looks at : [1, 9, 2, 6, 10]
Moves to : 3
Collect = 3 plants
Looks at : [2, 6, 7, 4, 8]
M

'Wait for Mama'

[9 4 3 2 1]
19
[7 6 0 0 0]
13
[9 9 8 1 0]
27
[8 5 3 1 0]
17
